name: music_player
description: A new music player

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # User Interface
  cupertino_icons:
  phosphor_flutter:
  lottie:
  shimmer:
  palette_generator:

  # State Management
  bloc:
  flutter_bloc:
  hydrated_bloc:

  # Database
  hive:
  hive_flutter:
  equatable:

  # Music
  flutter_media_metadata:
  just_audio:
  just_audio_background:
  storage_helper:
    path: packages/storage_helper

  # Json
  json_serializable:
  json_annotation:

  # Misc
  home_widget:
  url_launcher:
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  hive_generator:
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/anim/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
